{% set version = "0.11.7" %}

package:
  name: tobias
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tobias/tobias-{{ version }}.tar.gz
  sha256: 463b37f5f4f601b8aa9ec4b0c9880bb20eb098dc28d07e29f5ae2d6bfc5857fa

build:
  number: 0
  # Skipping py>=38 because dependency moods does not have Py3.8 builds.
  skip: True # [py<30 or py>=38]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pysam
    - matplotlib-base >=2
    - scikit-learn
    - pandas
    - pypdf2
    - xlsxwriter
    - pyBigWig
    - moods
    - pybedtools
    - adjusttext
    - svist4get ==1.2.22
    - xgboost >=0.71
    - boto3
    - pyyaml >=5.1
    - seaborn >=0.9.1
    - logomaker

test:
  commands:
    - "TOBIAS --help"

about:
  home: https://github.com/loosolab/TOBIAS/
  doc_url: https://github.com/loosolab/TOBIAS/wiki
  license: MIT
  summary: Transcription factor Occupancy prediction By Investigation of ATAC-seq Signal 
  description: |
    TOBIAS (Transcription factor Occupancy prediction By Investigation of ATAC-seq Signal) is a collection
    of command-line bioinformatics tools for performing footprinting analysis on ATAC-seq data. 

extra:
  recipe-maintainers:
    - msbentsen
    - jenzopr
